import { useState, useEffect } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import VanillaTilt from "vanilla-tilt";

import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Unstable_Grid2";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import TicketForm from "../components/TicketForm";

const Home: NextPage = (posts) => {
  const [search, setSearch] = useState("");

  const handleChange = (e: any) => {
    console.log(e);
    setSearch(e.target.value);
  };

  useEffect(() => {
    //@ts-ignore
    VanillaTilt.init(document.querySelectorAll(".tilter"), {
      scale: 1.1,
      perspective: 2000,
      speed: 500,
    });

    console.log(posts);
  }, []);

  return (
    <Box sx={{ backgroundColor: "#ececec" }}>
      <Head>
        <title>Maintenance System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TicketForm />

      <Grid container>
        <Grid
          display="flex"
          flexDirection="column"
          alignItems="center"
          xs={12}
          sx={{ py: 10 }}
        >
          <Typography variant="h4" color="initial" sx={{ mb: 2 }}>
            Locate your shop
          </Typography>
          <Grid xs={10} md={3}>
            <TextField
              placeholder="Search"
              variant="outlined"
              fullWidth
              value={search}
              onChange={handleChange}
            />
          </Grid>
        </Grid>
        <Grid container rowSpacing={3}>
          {[1, 2, 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16].map((el) => (
            <Grid
              key={el}
              xs={12}
              sm={4}
              md={3}
              xl={2}
              display="flex"
              justifyContent="center"
            >
              <Paper
                className="tilter"
                elevation={12}
                sx={{
                  borderRadius: 5,
                  minWidth: 200,
                  overflow: "hidden",
                }}
              >
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    px: 5,
                    mb: 8,
                  }}
                >
                  <img
                    src="/images/blob.png"
                    width={150}
                    style={{
                      zIndex: 0,
                      opacity: 0.3,
                      marginTop: 20,
                    }}
                  />
                  <img
                    src="/images/sampleshop.png_"
                    height={24}
                    style={{
                      marginTop: -80,
                      zIndex: 333,
                    }}
                  />
                </Box>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    mx: 2.1,
                    mb: 2,
                  }}
                >
                  <Typography variant="subtitle1">Store name</Typography>
                  <Typography variant="caption">LOCATION</Typography>
                  <Button
                    variant="contained"
                    size="small"
                    color="primary"
                    sx={{ borderRadius: 10, marginTop: 1, width: 80 }}
                  >
                    PICK
                  </Button>
                </Box>
              </Paper>
            </Grid>
          ))}
        </Grid>
      </Grid>
    </Box>
  );
};

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
}

export default Home;
