import { useState, useEffect } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import axios from "axios";
import { useQuery, useMutation } from "@tanstack/react-query";
import VanillaTilt from "vanilla-tilt";

import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Unstable_Grid2";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import AppDrawer from "../components/AppDrawer";
import TicketForm from "../components/TicketForm";
import { queryClient } from "./_app";

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);

  // * Get categories
  const { data: categories } = useQuery(
    ["Categories"],
    ({ queryKey }) => axios.get(queryKey[0]),
    { select: (data) => data.data.rows }
  );

  // * Get tickets
  const { data: tickets, isFetched } = useQuery(
    ["Tickets"],
    ({ queryKey }) => axios.get(queryKey[0]),
    {
      select: (data) => data.data,
      //onSuccess: () => queryClient.invalidateQueries(["Tickets"]),
    }
  );

  const handleChange = (e: any) => {
    console.log(e);
    setSearch(e.target.value);
  };

  useEffect(() => {
    //@ts-ignore
    VanillaTilt.init(document.querySelectorAll(".tilter"), {
      scale: 1.1,
      perspective: 2000,
      speed: 500,
    });
  }, []);

  return (
    <AppDrawer>
      <Box
        sx={
          {
            /*backgroundColor: "#ececec"*/
          }
        }
      >
        <Head>
          <title>Maintenance System</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <TicketForm categories={categories} open={open} setOpen={setOpen} />

        <Grid container>
          <Grid
            display="flex"
            flexDirection="column"
            alignItems="center"
            xs={12}
            sx={{ py: 10 }}
          >
            <Typography variant="h4" color="initial" sx={{ mb: 2 }}>
              Locate your shop
            </Typography>
            <Grid xs={10} md={3}>
              <TextField
                placeholder="Search"
                variant="outlined"
                fullWidth
                value={search}
                onChange={handleChange}
              />
            </Grid>
          </Grid>
          <Grid container rowSpacing={3}>
            {isFetched ? (
              tickets.map((ticket, i: Number) => (
                <Grid
                  key={i}
                  xs={12}
                  sm={4}
                  md={3}
                  xl={2}
                  display="flex"
                  justifyContent="center"
                >
                  <Paper
                    className="tilter"
                    elevation={12}
                    sx={{
                      borderRadius: 5,
                      minWidth: 200,
                      overflow: "hidden",
                    }}
                  >
                    <Box
                      sx={{
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        px: 5,
                        mb: 8,
                      }}
                    >
                      <img
                        src="/images/blob.png"
                        width={150}
                        style={{
                          zIndex: 0,
                          opacity: 0.3,
                          marginTop: 20,
                        }}
                      />
                      <img
                        src="/images/sampleshop.png"
                        height={24}
                        style={{
                          marginTop: -80,
                          zIndex: 333,
                        }}
                      />
                    </Box>
                    <Box
                      sx={{
                        display: "flex",
                        flexDirection: "column",
                        mx: 2.1,
                        mb: 2,
                      }}
                    >
                      <Typography variant="caption">
                        Ticket {ticket._id}
                      </Typography>
                      <Typography variant="subtitle1">Store name</Typography>
                      <Typography variant="caption">LOCATION</Typography>
                      <Button
                        variant="contained"
                        size="small"
                        color="primary"
                        onClick={() => setOpen(true)}
                        sx={{ borderRadius: 10, marginTop: 1, width: 80 }}
                      >
                        PICK
                      </Button>
                    </Box>
                  </Paper>
                </Grid>
              ))
            ) : (
              <span>Loading</span>
            )}
          </Grid>
        </Grid>
      </Box>
    </AppDrawer>
  );
};

export default Home;
